version: '3.8'

services:

  database:
    image: postgres:15.1-alpine
    container_name: database
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ylab_pgdata_test:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - ylab_network_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - ylab_network_test
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:80"
    env_file:
      - .env
    command: sh -c "pytest -v"

networks:
  ylab_network_test:
    name: ylab_network_test
volumes:
  ylab_pgdata_test:
    name: ylab_pgdata_test
