version: '3'

services:
  database:
    image: postgres
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env
  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - database
    ports:
      - "8000:80"
    env_file:
      - .env
