version: '3.8'

services:

  database:
    image: postgres:15.1-alpine
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ylab_pgdata:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - database
    ports:
      - "8000:80"
    env_file:
      - .env

volumes:
  ylab_pgdata:
